from torch_dag_algorithms.pruning.losses.bkd_losses import bkd_loss
from torch_dag_algorithms.pruning.losses.entropy_losses import entropy_loss
from torch_dag_algorithms.pruning.losses.latency_losses import latency_loss
from torch_dag_algorithms.pruning.losses.multiplier import anneal