from torch_dag.patterns.crude_patterns import VertexSpec
from torch_dag.patterns.crude_patterns import LinearGraphPattern
from torch_dag.patterns.crude_patterns import ReverseGraphPattern
from torch_dag.patterns.crude_patterns import build_dag_from_sequential
from torch_dag.patterns.crude_patterns import replace_linear_pattern
from torch_dag.patterns.crude_patterns import replace_linear_pattern_with_dag

from torch_dag.patterns.specific_patterns import PRUNABLE_ATTENTION_PATTERN