#
# Copyright © TCL Research Europe. All rights reserved.
#
PRUNING_DEFAULT_MODE_NAME = 'default'
PRUNING_BLOCK_SNPE_MODE_NAME = 'block_snpe'
PRUNING_WHOLE_BLOCK_MODE_NAME = 'whole_block'
INITIAL_LOGITS_VALUE_FOR_PRUNING = 3.

DEFAULT_TEMPERATURE = 0.5
DEFAULT_TEMPERATURE_DECAY_RATE = 1.0
DEFAULT_NUM_TRAINING_STEPS = 100000
TEMPERATURE_LOWER_BOUND = 0.5
MULTIADDS_BASIS = 1000.
MAX_LOGITS_ABS_VALUE = 6.
BLOCK_SIZE_FOR_CHANNELS = 32
SIMPLE_ORBIT_LOGITS_MULTIPLIER = 0.01

