name: Heavy tests

on:
  workflow_dispatch:
  schedule:
    - cron: '45 12 1 * *' # 12:45 every day
permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
          image: ghcr.io/tclresearcheurope/torch-dag:0.0.9-pytorch-2.1.0-cuda11.8-cudnn8-runtime
          options: --user root
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.ghcr_token }}

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        pip install pytest-forked
        pytest tests --forked
        