name: Heavy tests - env

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 00:00 every Sunday
  pull_request:
    branches:
      - 'dependabot/pip/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.9'
      - name: Install torch-dag with dependencies
        run: pip install -e .
      - name: Run tests
        run: |
          pip install pytest-forked
          pytest tests --forked
