name: Heavy tests with env dependencies

on:
  pull_request:
    branches:
      - 'dependabot/pip/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install torch-dag with dependencies
        run: pip install -e .
      - name: Run tests
        run: |
          pip install pytest-forked
          pytest tests --forked
