name: Light tests

on:
  push:
    tags:
        - '!v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-tests:

    runs-on: ubuntu-latest
    container:
          image: registry.gitlab.com/tcl-research/auto-ml/devine/torch-dag:0.0.9-pytorch-2.1.0-timm-0.9.5-cuda11.8-cudnn8-runtime
          credentials:
            username: ${{ secrets.DOCKER_TCL_USER}}
            password: ${{ secrets.DOCKER_TCL_P}}
          options: --user root

    steps:
    - uses: actions/checkout@v4
    - name: Test with pytest
      run: pytest --light tests