name: Light tests - docker

on:
  push:
    tags:
      - '!v*'
    paths-ignore:
      - 'requirements.txt'
      - 'requirements-dev.txt'
      - 'docker/requirements-docker.txt'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'requirements.txt'
      - 'requirements-dev.txt'
      - 'docker/requirements-docker.txt'

permissions:
  contents: read
  packages: read

jobs:
  run-tests:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tclresearcheurope/torch-dag/image:0.0.9-pytorch-2.1.0-cuda11.8-cudnn8-runtime
      options: --user root


    steps:
      - uses: actions/checkout@v4
      - name: Test with pytest
        run: pytest --light tests