on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.9'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install build
      - name: Build package
        run: python -m build
      - name: Install built package
        run: python -m pip install dist/*.gz
      - name: Test package
        run: |
            python -m pip install pytest
            python -m pip install pytest-xdist
            python -m pip install pytest-forked
            pytest -n 1 tests --forked
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/*'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}